name: Builder
on: [push, pull_request]
env:
  MYSQL_HOST: localhost
  MYSQL_DATABASE: doggiedb
  MYSQL_USERNAME: doggiedb
  MYSQL_PASSWORD: doggiedb
  POSTGRES_HOST: localhost
  POSTGRES_DATABASE: doggiedb
  POSTGRES_USERNAME: doggiedb
  POSTGRES_PASSWORD: doggiedb
  REDIS_HOST: localhost
  REDIS_DATABASE: doggiedb
  MONGO_HOST: localhost
  MONGO_DATABASE: doggiedb
  MONGO_USERNAME: doggiedb
  MONGO_PASSWORD: doggiedb
jobs:
  macos:
    name: ${{ matrix.name }}
    runs-on: macOS-latest
    strategy:
      matrix:
        name: [macOS, macOS(SwiftPM)]
        include:
          - name: macOS
            use_xcodebuild: true
            sdk: macosx
            destination: 'platform=macOS'
            enable_codecov: true
          - name: macOS(SwiftPM)
            use_xcodebuild: false
    env:
      use_xcodebuild: ${{ matrix.use_xcodebuild }}
      sdk: ${{ matrix.sdk }}
      destination: ${{ matrix.destination }}
      enable_codecov: ${{ matrix.enable_codecov }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Upgrade Homebrew
      run: brew upgrade
    - name: Install mariadb
      run: brew install mysql@5.7 && brew link --force mysql@5.7
    - name: Set up MySQL databases and privileges
      run: |
          brew services start mysql@5.7 && brew services list
          until echo | mysql -u$USER; do sleep 1; done
          mysql -u$USER --batch <<-'SQL'
              CREATE USER $MYSQL_USERNAME@localhost IDENTIFIED BY '$MYSQL_PASSWORD';
              CREATE DATABASE $MYSQL_DATABASE;
              GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO $MYSQL_USERNAME@localhost;
          SQL
      timeout-minutes: 1
    - name: Install postgresql
      run: |
          export PATH="/usr/local/opt/postgresql/bin:$PATH"
          brew install postgresql
          initdb --locale=C -U $POSTGRES_USERNAME --pwfile=<(echo $POSTGRES_PASSWORD)
          pg_ctl start --wait
    - name: Install redis
      run: brew install redis
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
    - uses: codecov/codecov-action@v1
      if: ${{ matrix.enable_codecov }}
  ubuntu_swift_latest:
    name: latest-${{ matrix.image }}
    container: 
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        ports: 
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: ${{ env.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
      postgres:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DATABASE }}
      redis:
        image: redis
        ports: 
          - 6379:6379
      mongo: 
        image: mongo
        ports: 
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ env.MONGO_DATABASE }}
    strategy:
      matrix:
        image: [xenial, bionic, focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: apt-get update
    - name: Install libmongoc
      run: apt-get install -y libmongoc-1.0-0 libbson-1.0-0 libssl-dev
    - name: Install sqlite3
      run: apt-get install -y libsqlite3-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
      env:
        MYSQL_HOST: mysql
        POSTGRES_HOST: postgres
        REDIS_HOST: redis
        MONGO_HOST: mongo
  ubuntu_swift_nightly:
    name: ${{ matrix.image }}
    container:
      image: docker://swiftlang/swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb
        ports: 
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: ${{ env.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
      postgres:
        image: postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DATABASE }}
      redis:
        image: redis
        ports: 
          - 6379:6379
      mongo: 
        image: mongo
        ports: 
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ env.MONGO_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD: ${{ env.MONGO_PASSWORD }}
          MONGO_INITDB_DATABASE: ${{ env.MONGO_DATABASE }}
    continue-on-error: true
    strategy:
      matrix:
        image: [nightly-xenial, nightly-bionic, nightly-focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: apt-get update
    - name: Install libmongoc
      run: apt-get install -y libmongoc-1.0-0 libbson-1.0-0 libssl-dev
    - name: Install sqlite3
      run: apt-get install -y libsqlite3-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
      env:
        MYSQL_HOST: mysql
        POSTGRES_HOST: postgres
        REDIS_HOST: redis
        MONGO_HOST: mongo
