name: Builder
on: [push, pull_request]
jobs:
  darwin:
    name: macOS
    runs-on: macOS-latest
    env:
      use_xcodebuild: true
      sdk: macosx
      destination: 'platform=macOS'
      enable_codecov: true
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
    - uses: codecov/codecov-action@v1
  macos:
    name: macOS(SwiftPM)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      with:
        action: test
  ubuntu_swift_latest:
    name: latest-${{ matrix.image }}
    container: 
      image: docker://swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
      postgres:
        image: postgres
      redis:
        image: redis
      mongo: 
        image: mongo
    strategy:
      matrix:
        image: [xenial, bionic, focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: apt-get update
    - name: Install libmongoc
      run: apt-get install -y libmongoc-1.0-0 libbson-1.0-0 libssl-dev
    - name: Install sqlite3
      run: apt-get install -y libsqlite3-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      env:
          MYSQL_HOST: mysql
          POSTGRES_HOST: postgres
          REDIS_HOST: redis
          MONGO_HOST: mongo
      with:
        action: test
  ubuntu_swift_nightly:
    name: ${{ matrix.image }}
    container:
      image: docker://swiftlang/swift:${{ matrix.image }}
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
      postgres:
        image: postgres
      redis:
        image: redis
      mongo: 
        image: mongo
    continue-on-error: true
    strategy:
      matrix:
        image: [nightly-xenial, nightly-bionic, nightly-focal]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Prepare		
      run: apt-get update
    - name: Install libmongoc
      run: apt-get install -y libmongoc-1.0-0 libbson-1.0-0 libssl-dev
    - name: Install sqlite3
      run: apt-get install -y libsqlite3-dev
    - name: Build
      uses: SusanDoggie/swift-action@main
      with:
        action: build
    - name: Run tests
      uses: SusanDoggie/swift-action@main
      env:
          MYSQL_HOST: mysql
          POSTGRES_HOST: postgres
          REDIS_HOST: redis
          MONGO_HOST: mongo
      with:
        action: test
