#!/bin/bash
set -e

echo ::group::Starting PostgreSQL service

export PATH="/usr/local/opt/postgresql/bin:$PATH" PGDATA=/tmp/postgres-test

brew install postgresql

initdb --locale=C -U $POSTGRES_USERNAME --pwfile=<(echo $POSTGRES_PASSWORD)
pg_ctl start --wait

echo ::endgroup::

echo ::group::Starting Redis service

brew install redis && brew services start redis

echo ::endgroup::

echo ::group::Starting MongoDB service

mkdir -p /data/db
chown -R `id -un` /data/db
mongod --port 27017 --dbpath /data/db/rs0 --replSet ${MONGO_REPLICA_SET} --bind_ip localhost

sleep 1
TIMER=0

until echo | mongo 'admin' --eval 'quit(0)'; do
  sleep 1
  echo "."
  TIMER=$((TIMER + 1))

  if [[ $TIMER -eq 20 ]]; then
    echo "MongoDB did not initialize within 20 seconds. Exiting."
    exit 2
  fi
done

mongo --eval "
  rs.initiate({
    _id: '${MONGO_REPLICA_SET}',
    members: [{
      _id: 0,
      host: 'localhost'
    }]
  })
"

sleep 1

mongo admin --eval "
  db.createUser({
    user: '${MONGO_USERNAME}',
    pwd: '${MONGO_PASSWORD}',
    roles: [{
      role: 'root',
      db: '${MONGO_AUTHSOURCE}'
    }]
  })
"

echo ::endgroup::