#!/bin/bash
set -e

echo ::group::Starting PostgreSQL service

export PATH="/usr/local/opt/postgresql/bin:$PATH" PGDATA=/tmp/postgres-test

brew install postgresql

initdb --locale=C -U $POSTGRES_USERNAME --pwfile=<(echo $POSTGRES_PASSWORD)
pg_ctl start --wait

echo ::endgroup::

echo ::group::Starting Redis service

brew install redis && brew services start redis

echo ::endgroup::

echo ::group::Starting MongoDB service

echo "
systemLog:
  destination: file
  path: /usr/local/var/log/mongodb/mongo.log
  logAppend: true
storage:
  engine: wiredTiger
  dbPath: /data/db/${MONGO_REPLICA_SET}
net:
  bindIp: 127.0.0.1
replication:
  replSetName: ${MONGO_REPLICA_SET}
" > /usr/local/etc/mongod.conf

brew services start mongodb-community

sleep 1
TIMER=0

until echo | mongo 'admin' --eval 'quit(0)'; do
  sleep 1
  echo "."
  TIMER=$((TIMER + 1))

  if [[ $TIMER -eq 20 ]]; then
    echo "MongoDB did not initialize within 20 seconds. Exiting."
    exit 2
  fi
done

mongo --eval "
  rs.initiate({
    _id: '${MONGO_REPLICA_SET}',
    members: [{
      _id: 0,
      host: 'localhost'
    }]
  })
"

sleep 1

mongo admin --eval "
  db.createUser({
    user: '${MONGO_USERNAME}',
    pwd: '${MONGO_PASSWORD}',
    roles: [{
      role: 'root',
      db: '${MONGO_AUTHSOURCE}'
    }]
  })
"

echo ::endgroup::